
services:
  web-app:
    container_name: web-app
    image: node:20-alpine  # Using Node.js version 20 for better ES module support
    working_dir: /app
    volumes:
      - ./web-app:/app
    ports:
      - "5173:5173"
    networks:
      - internal
    # environment:
    #   - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true

  tile-converter:
    container_name: tile-converter
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./tile-converter:/app
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm run start"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - internal

  tileserver-gl:
    container_name: tileserver-gl
    image: maptiler/tileserver-gl
    volumes:
      - ./tileserver:/data
    ports:
      - "8080:8080"
    command: --config /data/tileserver.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - internal

networks:
  internal:
    driver: bridge
